/**
 * @file yields-tracker-integration.ts
 * @description Bridge module connecting the WhaleTrucker Yields Tracker to
 *   the AssetTracker smart contract deployed on Polkadot Hub.
 *
 * Responsibilities:
 *  - Asset data synchronisation (Reef / EVM format → Polkadot format)
 *  - Real-time balance queries
 *  - Yield calculation and on-chain recording
 *  - Contract event listeners
 *  - Data export / import utilities
 *
 * Usage:
 *   import { YieldsTrackerBridge } from './yields-tracker-integration';
 *   const bridge = new YieldsTrackerBridge({ network: 'testnet', contractAddress: '0x...' });
 *   await bridge.connect();
 *   await bridge.syncAsset('0xUser', '0xToken', '1000000000000000000');
 */

import { ethers } from 'ethers';
import fs from 'fs';
import path from 'path';
import * as dotenv from 'dotenv';
import {
  getProvider,
  getWallet,
  getWalletFromMnemonic,
  getWssProvider,
  type NetworkName,
} from './polkadot-connection-config';

dotenv.config();

// ---------------------------------------------------------------------------
// ABI (minimal subset – full ABI is generated by the compiler)
// ---------------------------------------------------------------------------

const ASSET_TRACKER_ABI = [
  'function trackAsset(address user, address token, uint256 amount) external',
  'function trackAssetBatch(address[] users, address[] tokens, uint256[] amounts) external',
  'function updateYield(address user, address token, uint256 yieldAmount) external',
  'function requestXcmStateUpdate(uint32 targetChain, address user, address token) external',
  'function getBalance(address user, address token) external view returns (uint256)',
  'function getYield(address user, address token) external view returns (uint256)',
  'function getTrackedTokens(address user) external view returns (address[])',
  'function getAssetSummary(address user, address token) external view returns (uint256 balance, uint256 totalYield)',
  'event AssetTracked(address indexed user, address indexed token, uint256 oldAmount, uint256 newAmount)',
  'event YieldUpdated(address indexed user, address indexed token, uint256 yieldAmount, uint256 totalYield)',
  'event XcmStateUpdateRequested(uint32 indexed targetChain, address indexed user, address indexed token, uint256 balance)',
];

// ---------------------------------------------------------------------------
// Type Definitions
// ---------------------------------------------------------------------------

/** Configuration for constructing a YieldsTrackerBridge. */
export interface BridgeConfig {
  /** Target network. Defaults to value of NETWORK env var or "testnet". */
  network?: NetworkName;
  /** Address of the deployed AssetTracker contract. */
  contractAddress: string;
  /** Optional override – provide a pre-built signer/provider. */
  signer?: ethers.Signer;
}

/**
 * Reef/EVM asset record (format emitted by the existing Yields Tracker).
 * Amounts are passed as strings to avoid JS integer overflow with large
 * 18-decimal-place token quantities.
 */
export interface ReefAssetRecord {
  /** Reef account address (EVM-compatible `0x…`). */
  reefAddress: string;
  /** ERC-20 token contract address. */
  tokenAddress: string;
  /** Balance in token base units (uint256 as decimal string). */
  balance: string;
  /** Yield earned since last sync in token base units (decimal string). */
  yieldEarned?: string;
  /** ISO-8601 timestamp of the data snapshot. */
  timestamp?: string;
}

/** Single on-chain balance + yield summary. */
export interface AssetSummary {
  user: string;
  token: string;
  balance: bigint;
  totalYield: bigint;
}

/** Serialisable export format for data portability. */
export interface ExportPayload {
  exportedAt: string;
  network: string;
  contractAddress: string;
  records: Array<{
    user: string;
    token: string;
    balance: string;
    totalYield: string;
  }>;
}

// ---------------------------------------------------------------------------
// YieldsTrackerBridge
// ---------------------------------------------------------------------------

/**
 * High-level bridge between the WhaleTrucker Yields Tracker and the
 * AssetTracker Polkadot Hub smart contract.
 */
export class YieldsTrackerBridge {
  private readonly config: Required<BridgeConfig>;
  private provider?: ethers.JsonRpcProvider;
  private wsProvider?: ethers.WebSocketProvider;
  private contract?: ethers.Contract;
  private signer?: ethers.Signer;

  constructor(config: BridgeConfig) {
    this.config = {
      network: config.network ?? 'testnet',
      contractAddress: config.contractAddress,
      signer: config.signer ?? (undefined as unknown as ethers.Signer),
    };
  }

  // -------------------------------------------------------------------------
  // Lifecycle
  // -------------------------------------------------------------------------

  /**
   * Establishes a connection to the Polkadot Hub RPC endpoint and wires up
   * the AssetTracker contract instance with a signer.
   */
  async connect(): Promise<void> {
    console.log(
      `[bridge] Connecting to ${this.config.network} at contract ${this.config.contractAddress} ...`,
    );

    if (this.config.signer) {
      this.signer = this.config.signer;
      this.provider = this.signer.provider as ethers.JsonRpcProvider;
    } else {
      this.provider = await getProvider(this.config.network);

      if (process.env.PRIVATE_KEY) {
        this.signer = getWallet(this.provider);
      } else if (process.env.MNEMONIC) {
        this.signer = getWalletFromMnemonic(this.provider);
      } else {
        throw new Error(
          '[bridge] Neither PRIVATE_KEY nor MNEMONIC is set. ' +
            'Read-only queries will still work, but write operations will fail.',
        );
      }
    }

    this.contract = new ethers.Contract(
      this.config.contractAddress,
      ASSET_TRACKER_ABI,
      this.signer ?? this.provider,
    );

    console.log('[bridge] Connected.');
  }

  /** Disconnects any WebSocket provider subscriptions. */
  disconnect(): void {
    if (this.wsProvider) {
      this.wsProvider.destroy();
      this.wsProvider = undefined;
    }
    console.log('[bridge] Disconnected.');
  }

  // -------------------------------------------------------------------------
  // Data Transformation
  // -------------------------------------------------------------------------

  /**
   * Transforms a Reef/EVM AssetRecord into Polkadot-compatible parameters.
   * Normalises the balance to a `bigint` for on-chain calls.
   *
   * @param record - Incoming Reef asset record.
   * @returns Tuple of `[userAddress, tokenAddress, balanceBigInt, yieldBigInt]`.
   */
  transformReefRecord(
    record: ReefAssetRecord,
  ): [string, string, bigint, bigint] {
    const user = ethers.getAddress(record.reefAddress);
    const token = ethers.getAddress(record.tokenAddress);
    const balance = BigInt(record.balance);
    const yieldEarned = record.yieldEarned ? BigInt(record.yieldEarned) : 0n;
    return [user, token, balance, yieldEarned];
  }

  // -------------------------------------------------------------------------
  // Write Operations
  // -------------------------------------------------------------------------

  /**
   * Synchronises a single asset balance to the on-chain tracker.
   *
   * @param user    User EVM address.
   * @param token   Token EVM address.
   * @param balance New balance in token base units (decimal string or bigint).
   * @returns Transaction hash.
   */
  async syncAsset(
    user: string,
    token: string,
    balance: string | bigint,
  ): Promise<string> {
    this.assertConnected();
    const tx = await (this.contract as ethers.Contract).trackAsset(
      user,
      token,
      BigInt(balance),
    ) as ethers.TransactionResponse;
    console.log(`[bridge] syncAsset tx: ${tx.hash}`);
    await tx.wait();
    return tx.hash;
  }

  /**
   * Batch-synchronises an array of Reef asset records in a single transaction.
   *
   * @param records - Array of Reef format asset records.
   * @returns Transaction hash.
   */
  async syncBatch(records: ReefAssetRecord[]): Promise<string> {
    this.assertConnected();

    const users: string[]   = [];
    const tokens: string[]  = [];
    const amounts: bigint[] = [];
    const yieldUpdates: Array<[string, string, bigint]> = [];

    for (const record of records) {
      const [user, token, balance, yieldEarned] = this.transformReefRecord(record);
      users.push(user);
      tokens.push(token);
      amounts.push(balance);
      if (yieldEarned > 0n) {
        yieldUpdates.push([user, token, yieldEarned]);
      }
    }

    const batchTx = await (this.contract as ethers.Contract).trackAssetBatch(
      users,
      tokens,
      amounts,
    ) as ethers.TransactionResponse;
    console.log(`[bridge] syncBatch tx: ${batchTx.hash} (${records.length} records)`);
    await batchTx.wait();

    // Record any associated yield updates sequentially.
    for (const [user, token, yieldEarned] of yieldUpdates) {
      await this.recordYield(user, token, yieldEarned);
    }

    return batchTx.hash;
  }

  /**
   * Records incremental yield on-chain for a user/token pair.
   *
   * @param user        Beneficiary EVM address.
   * @param token       Token EVM address.
   * @param yieldAmount Yield in token base units (decimal string or bigint).
   * @returns Transaction hash.
   */
  async recordYield(
    user: string,
    token: string,
    yieldAmount: string | bigint,
  ): Promise<string> {
    this.assertConnected();
    const tx = await (this.contract as ethers.Contract).updateYield(
      user,
      token,
      BigInt(yieldAmount),
    ) as ethers.TransactionResponse;
    console.log(`[bridge] recordYield tx: ${tx.hash}`);
    await tx.wait();
    return tx.hash;
  }

  /**
   * Requests a cross-chain XCM state synchronisation for a user/token.
   *
   * @param targetChain Parachain ID of the destination.
   * @param user        User EVM address.
   * @param token       Token EVM address.
   * @returns Transaction hash.
   */
  async requestXcmSync(
    targetChain: number,
    user: string,
    token: string,
  ): Promise<string> {
    this.assertConnected();
    const tx = await (this.contract as ethers.Contract).requestXcmStateUpdate(
      targetChain,
      user,
      token,
    ) as ethers.TransactionResponse;
    console.log(`[bridge] requestXcmSync tx: ${tx.hash}`);
    await tx.wait();
    return tx.hash;
  }

  // -------------------------------------------------------------------------
  // Read Operations
  // -------------------------------------------------------------------------

  /**
   * Queries the on-chain tracked balance for a user/token pair.
   *
   * @param user  User EVM address.
   * @param token Token EVM address.
   * @returns Balance as `bigint`.
   */
  async queryBalance(user: string, token: string): Promise<bigint> {
    this.assertConnected();
    return (this.contract as ethers.Contract).getBalance(user, token) as Promise<bigint>;
  }

  /**
   * Queries the cumulative on-chain yield for a user/token pair.
   *
   * @param user  User EVM address.
   * @param token Token EVM address.
   * @returns Total yield as `bigint`.
   */
  async queryYield(user: string, token: string): Promise<bigint> {
    this.assertConnected();
    return (this.contract as ethers.Contract).getYield(user, token) as Promise<bigint>;
  }

  /**
   * Returns a full on-chain summary (balance + yield) for a user/token pair.
   *
   * @param user  User EVM address.
   * @param token Token EVM address.
   * @returns `AssetSummary` object.
   */
  async queryAssetSummary(user: string, token: string): Promise<AssetSummary> {
    this.assertConnected();
    const [balance, totalYield]: [bigint, bigint] = await (
      this.contract as ethers.Contract
    ).getAssetSummary(user, token);
    return { user, token, balance, totalYield };
  }

  /**
   * Returns all tokens tracked for a given user.
   *
   * @param user  User EVM address.
   * @returns Array of token addresses.
   */
  async queryTrackedTokens(user: string): Promise<string[]> {
    this.assertConnected();
    return (this.contract as ethers.Contract).getTrackedTokens(user) as Promise<string[]>;
  }

  // -------------------------------------------------------------------------
  // Event Listeners
  // -------------------------------------------------------------------------

  /**
   * Subscribes to `AssetTracked` events via a WebSocket provider and invokes
   * `callback` for each event received.
   *
   * @param callback - Function called with `(user, token, oldAmount, newAmount)`.
   */
  listenAssetTracked(
    callback: (user: string, token: string, oldAmount: bigint, newAmount: bigint) => void,
  ): void {
    const wsContract = this.getWsContract();
    wsContract.on(
      'AssetTracked',
      (user: string, token: string, oldAmount: bigint, newAmount: bigint) => {
        callback(user, token, oldAmount, newAmount);
      },
    );
    console.log('[bridge] Listening for AssetTracked events ...');
  }

  /**
   * Subscribes to `YieldUpdated` events.
   *
   * @param callback - Function called with `(user, token, yieldAmount, totalYield)`.
   */
  listenYieldUpdated(
    callback: (user: string, token: string, yieldAmount: bigint, totalYield: bigint) => void,
  ): void {
    const wsContract = this.getWsContract();
    wsContract.on(
      'YieldUpdated',
      (user: string, token: string, yieldAmount: bigint, totalYield: bigint) => {
        callback(user, token, yieldAmount, totalYield);
      },
    );
    console.log('[bridge] Listening for YieldUpdated events ...');
  }

  // -------------------------------------------------------------------------
  // Export / Import Utilities
  // -------------------------------------------------------------------------

  /**
   * Exports a snapshot of on-chain data for the given user addresses to a
   * JSON file.
   *
   * @param users         Array of user EVM addresses to export.
   * @param outputPath    Destination file path for the JSON export.
   */
  async exportSnapshot(users: string[], outputPath: string): Promise<void> {
    this.assertConnected();
    const payload: ExportPayload = {
      exportedAt: new Date().toISOString(),
      network: this.config.network,
      contractAddress: this.config.contractAddress,
      records: [],
    };

    for (const user of users) {
      const tokens = await this.queryTrackedTokens(user);
      for (const token of tokens) {
        const summary = await this.queryAssetSummary(user, token);
        payload.records.push({
          user,
          token,
          balance: summary.balance.toString(),
          totalYield: summary.totalYield.toString(),
        });
      }
    }

    fs.writeFileSync(outputPath, JSON.stringify(payload, null, 2));
    console.log(`[bridge] Snapshot exported to: ${outputPath}`);
  }

  /**
   * Imports and syncs an exported payload back to the contract.
   * Useful for migrating state between networks or recovering from outages.
   *
   * @param inputPath - Path to a JSON file previously created by `exportSnapshot`.
   * @returns Number of records synced.
   */
  async importSnapshot(inputPath: string): Promise<number> {
    this.assertConnected();
    const raw = fs.readFileSync(inputPath, 'utf-8');
    const payload = JSON.parse(raw) as ExportPayload;

    console.log(
      `[bridge] Importing ${payload.records.length} records from: ${inputPath}`,
    );

    const users   = payload.records.map((r) => r.user);
    const tokens  = payload.records.map((r) => r.token);
    const amounts = payload.records.map((r) => BigInt(r.balance));

    const batchTx = await (this.contract as ethers.Contract).trackAssetBatch(
      users,
      tokens,
      amounts,
    ) as ethers.TransactionResponse;
    await batchTx.wait();

    console.log(`[bridge] Import complete. tx: ${batchTx.hash}`);
    return payload.records.length;
  }

  // -------------------------------------------------------------------------
  // Private Helpers
  // -------------------------------------------------------------------------

  private assertConnected(): void {
    if (!this.contract) {
      throw new Error('[bridge] Not connected. Call connect() first.');
    }
  }

  private getWsContract(): ethers.Contract {
    if (!this.wsProvider) {
      this.wsProvider = getWssProvider(this.config.network);
    }
    return new ethers.Contract(
      this.config.contractAddress,
      ASSET_TRACKER_ABI,
      this.wsProvider,
    );
  }
}

// ---------------------------------------------------------------------------
// Convenience Factory
// ---------------------------------------------------------------------------

/**
 * Creates and connects a `YieldsTrackerBridge` in one call.
 *
 * @param contractAddress - Deployed AssetTracker contract address.
 * @param network         - Target network (default: env NETWORK or "testnet").
 * @returns A connected `YieldsTrackerBridge` instance.
 *
 * @example
 * ```typescript
 * const bridge = await createBridge('0xYourContractAddress');
 * const balance = await bridge.queryBalance('0xUser', '0xToken');
 * ```
 */
export async function createBridge(
  contractAddress: string,
  network?: NetworkName,
): Promise<YieldsTrackerBridge> {
  const bridge = new YieldsTrackerBridge({ contractAddress, network });
  await bridge.connect();
  return bridge;
}

// ---------------------------------------------------------------------------
// Deployed Address Loader
// ---------------------------------------------------------------------------

/**
 * Loads a deployed contract address from `deployed-addresses.json`.
 *
 * @param network      - Network key.
 * @param contractName - Contract name (default: "AssetTracker").
 * @returns Deployed address string.
 * @throws Error if the address file or entry is missing.
 */
export function loadDeployedAddress(
  network: NetworkName,
  contractName = 'AssetTracker',
): string {
  const filePath = path.resolve(__dirname, 'deployed-addresses.json');
  if (!fs.existsSync(filePath)) {
    throw new Error(
      `[bridge] deployed-addresses.json not found. Deploy the contract first.`,
    );
  }
  const addresses = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as Record<
    string,
    Record<string, string>
  >;
  const address = addresses[network]?.[contractName];
  if (!address) {
    throw new Error(
      `[bridge] No address for "${contractName}" on "${network}" in deployed-addresses.json.`,
    );
  }
  return address;
}
