name: PR Docs Link Check

on:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          # สแกนทุกไฟล์ .md ใน Repo
          args: '--verbose --no-progress "./**/*.md"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
